name: Main

on:
  push:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Build
      run: cargo build --release --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run Clippy
      run: cargo clippy --verbose
      
    - name: Run Rustfmt
      run: cargo fmt --check --verbose
      
    - name: Copy binary
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: target/release/contest-back
        remote_path: ${{ secrets.SERVER_FOLDER }}
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH }}
        
    - name: Reload systemd service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH }}
        script: sudo -n systemctl reload ${{ secrets.SERVER_SERVICE }}.service
